// Generated by `supabase gen types typescript --project-id gpnsaswidreusgkyemvi`.
// Re-run after every migration. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agent_steps: {
        Row: {
          agent: string
          cache_creation_tokens: number
          cache_read_tokens: number
          cost_usd: number
          finished_at: string | null
          id: string
          input_summary: string | null
          input_tokens: number
          metadata: Json
          model: string
          output_summary: string | null
          output_tokens: number
          position: number
          run_id: string
          started_at: string
          status: string
          steps: number
          stop_reason: string | null
          tool_calls: number
        }
        Insert: {
          agent: string
          cache_creation_tokens?: number
          cache_read_tokens?: number
          cost_usd?: number
          finished_at?: string | null
          id?: string
          input_summary?: string | null
          input_tokens?: number
          metadata?: Json
          model: string
          output_summary?: string | null
          output_tokens?: number
          position: number
          run_id: string
          started_at?: string
          status?: string
          steps?: number
          stop_reason?: string | null
          tool_calls?: number
        }
        Update: {
          agent?: string
          cache_creation_tokens?: number
          cache_read_tokens?: number
          cost_usd?: number
          finished_at?: string | null
          id?: string
          input_summary?: string | null
          input_tokens?: number
          metadata?: Json
          model?: string
          output_summary?: string | null
          output_tokens?: number
          position?: number
          run_id?: string
          started_at?: string
          status?: string
          steps?: number
          stop_reason?: string | null
          tool_calls?: number
        }
        Relationships: [
          {
            foreignKeyName: "agent_steps_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
        ]
      }
      issues: {
        Row: {
          author_login: string | null
          body: string | null
          created_at: string
          duplicates_of: number[]
          fixable: boolean | null
          github_issue_id: number | null
          github_issue_number: number
          id: string
          labels: string[]
          repo_id: string
          state: string
          title: string
          triage_next_action: string | null
          triage_reproducible: string | null
          triage_scope: string | null
          triage_severity: string | null
          triage_summary: string | null
          triage_type: string | null
          triaged_at: string | null
          updated_at: string
        }
        Insert: {
          author_login?: string | null
          body?: string | null
          created_at?: string
          duplicates_of?: number[]
          fixable?: boolean | null
          github_issue_id?: number | null
          github_issue_number: number
          id?: string
          labels?: string[]
          repo_id: string
          state?: string
          title: string
          triage_next_action?: string | null
          triage_reproducible?: string | null
          triage_scope?: string | null
          triage_severity?: string | null
          triage_summary?: string | null
          triage_type?: string | null
          triaged_at?: string | null
          updated_at?: string
        }
        Update: {
          author_login?: string | null
          body?: string | null
          created_at?: string
          duplicates_of?: number[]
          fixable?: boolean | null
          github_issue_id?: number | null
          github_issue_number?: number
          id?: string
          labels?: string[]
          repo_id?: string
          state?: string
          title?: string
          triage_next_action?: string | null
          triage_reproducible?: string | null
          triage_scope?: string | null
          triage_severity?: string | null
          triage_summary?: string | null
          triage_type?: string | null
          triaged_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "issues_repo_id_fkey"
            columns: ["repo_id"]
            isOneToOne: false
            referencedRelation: "repos"
            referencedColumns: ["id"]
          },
        ]
      }
      pull_requests: {
        Row: {
          additions: number | null
          base_branch: string
          branch: string
          created_at: string
          deletions: number | null
          files_changed: string[]
          github_pr_id: number | null
          github_pr_number: number
          id: string
          issue_id: string | null
          merged: boolean
          merged_at: string | null
          ready_for_review: boolean
          repo_id: string
          run_id: string | null
          state: string
          title: string
          updated_at: string
          url: string
        }
        Insert: {
          additions?: number | null
          base_branch: string
          branch: string
          created_at?: string
          deletions?: number | null
          files_changed?: string[]
          github_pr_id?: number | null
          github_pr_number: number
          id?: string
          issue_id?: string | null
          merged?: boolean
          merged_at?: string | null
          ready_for_review?: boolean
          repo_id: string
          run_id?: string | null
          state?: string
          title: string
          updated_at?: string
          url: string
        }
        Update: {
          additions?: number | null
          base_branch?: string
          branch?: string
          created_at?: string
          deletions?: number | null
          files_changed?: string[]
          github_pr_id?: number | null
          github_pr_number?: number
          id?: string
          issue_id?: string | null
          merged?: boolean
          merged_at?: string | null
          ready_for_review?: boolean
          repo_id?: string
          run_id?: string | null
          state?: string
          title?: string
          updated_at?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "pull_requests_issue_id_fkey"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pull_requests_repo_id_fkey"
            columns: ["repo_id"]
            isOneToOne: false
            referencedRelation: "repos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pull_requests_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
        ]
      }
      repos: {
        Row: {
          config: Json
          created_at: string
          enabled: boolean
          github_repo_id: number | null
          id: string
          installation_id: number | null
          installed_by_user: string | null
          name: string
          owner: string
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          enabled?: boolean
          github_repo_id?: number | null
          id?: string
          installation_id?: number | null
          installed_by_user?: string | null
          name: string
          owner: string
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          enabled?: boolean
          github_repo_id?: number | null
          id?: string
          installation_id?: number | null
          installed_by_user?: string | null
          name?: string
          owner?: string
          updated_at?: string
        }
        Relationships: []
      }
      runs: {
        Row: {
          finished_at: string | null
          github_run_id: number | null
          github_run_url: string | null
          id: string
          issue_id: string | null
          outcome: string | null
          pr_id: string | null
          repo_id: string
          started_at: string
          status: string
          total_cache_creation_tokens: number
          total_cache_read_tokens: number
          total_cost_usd: number
          total_input_tokens: number
          total_output_tokens: number
          total_runtime_ms: number | null
          trigger: string
          trigger_payload: Json | null
        }
        Insert: {
          finished_at?: string | null
          github_run_id?: number | null
          github_run_url?: string | null
          id?: string
          issue_id?: string | null
          outcome?: string | null
          pr_id?: string | null
          repo_id: string
          started_at?: string
          status?: string
          total_cache_creation_tokens?: number
          total_cache_read_tokens?: number
          total_cost_usd?: number
          total_input_tokens?: number
          total_output_tokens?: number
          total_runtime_ms?: number | null
          trigger: string
          trigger_payload?: Json | null
        }
        Update: {
          finished_at?: string | null
          github_run_id?: number | null
          github_run_url?: string | null
          id?: string
          issue_id?: string | null
          outcome?: string | null
          pr_id?: string | null
          repo_id?: string
          started_at?: string
          status?: string
          total_cache_creation_tokens?: number
          total_cache_read_tokens?: number
          total_cost_usd?: number
          total_input_tokens?: number
          total_output_tokens?: number
          total_runtime_ms?: number | null
          trigger?: string
          trigger_payload?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "runs_issue_id_fkey"
            columns: ["issue_id"]
            isOneToOne: false
            referencedRelation: "issues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "runs_pr_id_fkey"
            columns: ["pr_id"]
            isOneToOne: false
            referencedRelation: "pull_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "runs_repo_id_fkey"
            columns: ["repo_id"]
            isOneToOne: false
            referencedRelation: "repos"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
